export const HOT_RELOAD_CONFIG_KEYS = new Set([
  "BELLDANDY_WEB_GOVERNANCE_DETAIL_MODE",
  "BELLDANDY_WEB_EXPERIENCE_DRAFT_GENERATE_NOTICE_ENABLED",
  "BELLDANDY_ATTACHMENT_MAX_FILE_BYTES",
  "BELLDANDY_ATTACHMENT_MAX_TOTAL_BYTES",
  "BELLDANDY_ATTACHMENT_TEXT_CHAR_LIMIT",
  "BELLDANDY_ATTACHMENT_TEXT_TOTAL_CHAR_LIMIT",
  "BELLDANDY_AUDIO_TRANSCRIPT_APPEND_CHAR_LIMIT",
  "BELLDANDY_TTS_ENABLED",
  "BELLDANDY_TTS_PROVIDER",
  "BELLDANDY_TTS_VOICE",
  "BELLDANDY_TTS_MODEL",
  "BELLDANDY_TTS_OPENAI_API_KEY",
  "BELLDANDY_TTS_OPENAI_BASE_URL",
  "BELLDANDY_IMAGE_ENABLED",
  "BELLDANDY_IMAGE_PROVIDER",
  "BELLDANDY_IMAGE_OPENAI_API_KEY",
  "BELLDANDY_IMAGE_OPENAI_BASE_URL",
  "BELLDANDY_IMAGE_MODEL",
  "BELLDANDY_IMAGE_OUTPUT_FORMAT",
  "BELLDANDY_IMAGE_TIMEOUT_MS",
  "BELLDANDY_IMAGE_UNDERSTAND_ENABLED",
  "BELLDANDY_IMAGE_UNDERSTAND_AUTO_ON_ATTACHMENT",
  "BELLDANDY_BROWSER_SCREENSHOT_AUTO_UNDERSTAND",
  "BELLDANDY_CAMERA_SNAP_AUTO_UNDERSTAND",
  "BELLDANDY_SCREEN_CAPTURE_AUTO_UNDERSTAND",
  "BELLDANDY_IMAGE_UNDERSTAND_PROVIDER",
  "BELLDANDY_IMAGE_UNDERSTAND_OPENAI_API_KEY",
  "BELLDANDY_IMAGE_UNDERSTAND_OPENAI_BASE_URL",
  "BELLDANDY_IMAGE_UNDERSTAND_MODEL",
  "BELLDANDY_IMAGE_UNDERSTAND_TIMEOUT_MS",
  "BELLDANDY_IMAGE_UNDERSTAND_PROMPT",
  "BELLDANDY_IMAGE_UNDERSTAND_MAX_INPUT_MB",
  "BELLDANDY_VIDEO_UNDERSTAND_ENABLED",
  "BELLDANDY_VIDEO_UNDERSTAND_AUTO_ON_ATTACHMENT",
  "BELLDANDY_VIDEO_UNDERSTAND_PROVIDER",
  "BELLDANDY_VIDEO_UNDERSTAND_OPENAI_API_KEY",
  "BELLDANDY_VIDEO_UNDERSTAND_OPENAI_BASE_URL",
  "BELLDANDY_VIDEO_UNDERSTAND_MODEL",
  "BELLDANDY_VIDEO_UNDERSTAND_TIMEOUT_MS",
  "BELLDANDY_VIDEO_UNDERSTAND_TRANSPORT",
  "BELLDANDY_VIDEO_UNDERSTAND_FPS",
  "BELLDANDY_VIDEO_UNDERSTAND_AUTO_ATTACHMENT_MAX_TIMELINE_ITEMS",
  "BELLDANDY_VIDEO_UNDERSTAND_AUTO_ATTACHMENT_SUMMARY_CHAR_LIMIT",
  "BELLDANDY_VIDEO_UNDERSTAND_PROMPT",
  "BELLDANDY_VIDEO_UNDERSTAND_MAX_INPUT_MB",
  "BELLDANDY_VIDEO_FILE_API_URL",
  "BELLDANDY_VIDEO_FILE_API_KEY",
  "BELLDANDY_STT_PROVIDER",
  "BELLDANDY_STT_MODEL",
  "BELLDANDY_STT_LANGUAGE",
  "BELLDANDY_STT_OPENAI_API_KEY",
  "BELLDANDY_STT_OPENAI_BASE_URL",
  "BELLDANDY_STT_GROQ_API_KEY",
  "BELLDANDY_STT_GROQ_BASE_URL",
  "BELLDANDY_EXTERNAL_OUTBOUND_REQUIRE_CONFIRMATION",
  "BELLDANDY_EMAIL_OUTBOUND_REQUIRE_CONFIRMATION",
  "BELLDANDY_COMMUNITY_API_ENABLED",
  "BELLDANDY_COMMUNITY_API_TOKEN",
  "BELLDANDY_WEBHOOK_PREAUTH_MAX_BYTES",
  "BELLDANDY_WEBHOOK_PREAUTH_TIMEOUT_MS",
  "BELLDANDY_WEBHOOK_RATE_LIMIT_WINDOW_MS",
  "BELLDANDY_WEBHOOK_RATE_LIMIT_MAX_REQUESTS",
  "BELLDANDY_WEBHOOK_RATE_LIMIT_MAX_TRACKED_KEYS",
  "BELLDANDY_WEBHOOK_MAX_IN_FLIGHT_PER_KEY",
  "BELLDANDY_WEBHOOK_MAX_IN_FLIGHT_TRACKED_KEYS",
  "DASHSCOPE_API_KEY",
]);

export function isHotReloadConfigKey(key: string): boolean {
  return HOT_RELOAD_CONFIG_KEYS.has(key);
}

export function areAllConfigKeysHotReload(keys: Iterable<string>): boolean {
  let hasAny = false;
  for (const key of keys) {
    hasAny = true;
    if (!isHotReloadConfigKey(key)) {
      return false;
    }
  }
  return hasAny;
}
