import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(scriptDir, "..");
const packageJsonPath = path.join(rootDir, "package.json");
const outputPath = path.join(rootDir, "packages", "belldandy-core", "src", "version.generated.ts");

async function main() {
  const raw = await fs.readFile(packageJsonPath, "utf-8");
  const parsed = JSON.parse(raw);
  const version = typeof parsed.version === "string" ? parsed.version.trim() : "";

  if (!version) {
    throw new Error(`Missing valid "version" in ${packageJsonPath}`);
  }

  const content = [
    "// Auto-generated by scripts/generate-version.mjs. Do not edit.",
    `export const BELLDANDY_VERSION = ${JSON.stringify(version)};`,
    "",
  ].join("\n");

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, content, "utf-8");
  console.log(`[version] Generated ${path.relative(rootDir, outputPath)} (${version})`);
}

main().catch((err) => {
  console.error("[version] Failed to generate version file:", err);
  process.exit(1);
});
